services:
  orders-db:
    container_name: orders_database
    image: postgres:16.2
    volumes:
      - orders_db_data:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ordersdb

volumes:
  orders_db_data:

