// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from 'dotenv';
import path from 'node:path';
import { defineConfig } from 'prisma/config';

// Allows to load environment variables from a .env file located in the root directory of the project.
// It is necessary because launcher is the root directory of the project, and the .env file is located there.
// This configuration allows to execute database migrations from the root directory of the project.
dotenv.config();
dotenv.config({ path: path.resolve(__dirname, '../.env') });

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
